[theme]
base = "light"
primaryColor = "#fca311"
backgroundColor = "#f7f8fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#14213d"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
